parameters:
    projectm.project.project.class: DMKProjectM\Bundle\ProjectBundle\Entity\Project

services:
    projectm.project.project.manager:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%projectm.project.project.class%'
            - "@doctrine.orm.entity_manager"

    projectm.project.form.autocomplete.project.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%projectm.project.project.class%"
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: projectm_projects, acl_resource: projectm_project_view }
