navigation:
    menu_config:
        items:
            projectm_task_list:
                label: 'oro.task.entity_plural_label'
                route: 'projectm_task_index'
                position: 10
                extras:
                    routes: ['projectm_task_update', 'projectm_task_create', 'projectm_task_view']
                    description: 'Beschreibung'

        tree:
            application_menu:
                children:
                    dmkprojectm_tab:
                        children:
                            projectm_task_list: ~
    titles:
        projectm_task_index: ~
        projectm_task_view: '%entity.subject%'
        projectm_task_create: oro.ui.create_entity
        projectm_task_update: '%entity.subject% - Edit'
